### ISSUE TITLE
missing support in hebrew

### ISSUE THREAD

**Issue by eladmotola** [3scale/3scale_toolbox#230] opened 2019-12-13 10:40 UTC
Hey,

When I use the `3scale import openapi` command with a swagger file that contains Hebrew in the description its turn to gibberish in 3scale.

for example:

```
{
        "swagger": "2.0",
        "info": {
            "version": "v1",
            "title": "WebApplication1",
	    "description": "תיאור"
        },
        "host": "localhost:3873",
        "schemes": ["http"],
        "paths": {
            "/api/User": {
                "get": {
                    "tags": ["User"],
                    "operationId": "User_Get",
                    "consumes": [],
                    "produces": ["application/json", "text/json", "application/xml", "text/xml"],
                    "responses": {
                        "200": {
                            "description": "OK",
                            "schema": {
                                "type": "array",
                                "items": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "definitions": {}
 }
```

I've check and 3scale app support Hebrew.

**Comment by eguzki** [comment] 2019-12-13 10:47
Thanks for reporting. We will be reviewing ASAP

**Comment by eguzki** [comment] 2019-12-13 13:40
Did you run the toolbox with SaaS remote or on-prem remote? If on-prem, which is the 3scale version?

**Comment by eladmotola** [comment] 2019-12-13 13:42
on-prem version 2.6

**Comment by eguzki** [comment] 2019-12-13 14:37
The issue is that characters or letters are shown in reverse order?

When I import this char sequence `רואית` `\x05EA\x05D9\x05D0\x05D5\x05E8`, I see in the dashboard in reverse order, i.e.  `תיאור` `x05E8\x05D5\x05D9\x05EA`. Is that what you get?

**Comment by eladmotola** [comment] 2019-12-15 08:14
The issue is when I import swagger that contains Hebrew, I see gibberish

**Comment by eguzki** [comment] 2019-12-16 11:06
Make sure your json file is encoded in `utf-8`, which is the default encoding that JSON specification explicitly defines to be used. The utf-8 sequence of that string
```
תיאור
```
should be
```
\xd7a8 \xd795 \xd790 \xd799 \xd7aa
```
unicode sequence (internal representation) is
```
\u05E8\u05D5\u05D9\u05EA
```

I have run `3scale import openapi` on 3scale on-prem 2.6 and I send screenshot of what I see once imported.

![Screenshot_2019-12-16 Services - Show Red Hat 3scale API Management](https://user-images.githubusercontent.com/881529/70901705-9bd68100-1ffb-11ea-8f17-b189d0fd70b6.png)

What I see is the same string sequence, but in the reverse order, so that what is first becomes last and what is last becomes first. Is that effect happening to you? Or you are getting random characters?

**Comment by eladmotola** [comment] 2019-12-17 13:49
Hey, thank you for investigating.
I see that my files are encoded with `utf-8 without BOM`, so I think this is the problem. I tried to change them to `utf-8` but now Toolbox is yelling that something in the file is wrong, I will keep working on it.

On the other hand, the behavior that you found is not expected

**Comment by eguzki** [comment] 2019-12-18 10:45
Hi,

There is no issue with the order of the string. It was my IDE when copying the json who reversed the string, as my IDE is not aware about hebrew encoding being right-to-left. Once I fixed that, the string is correctly shown, as expected. 

`תיאור`: "description" :)

I had, though, to manipulate your openapi spec. `localhost` domain is protected and not allowed as `host`. You need to provide something else. I just replaced with 3scale's echo api service host. Besides, since no security requirement is specified, you need to tell the toolbox the default credentials user key

```
{
        "swagger": "2.0",
        "info": {
            "version": "v1",
            "title": "WebApplication1",
	    "description": "תיאור"
        },
        "host": "echo-api.3scale.net:443",
        "schemes": ["https"],
        "paths": {
            "/api/User": {
                "get": {
                    "tags": ["User"],
                    "operationId": "User_Get",
                    "consumes": [],
                    "produces": ["application/json", "text/json", "application/xml", "text/xml"],
                    "responses": {
                        "200": {
                            "description": "OK",
                            "schema": {
                                "type": "array",
                                "items": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "definitions": {}
 }
```
Run the command like this and should work

```
3scale -k import openapi -d mytenant~/tmp/hebrew.yaml --default-credentials-userkey 123456
```

Let us know if you have further issues. Happy to help.

**Comment by eladmotola** [comment] 2019-12-24 14:02
@eguzki it's look like there is a problem on Windows machines. When I run the import command from linux the Hebrew works fine.

**Comment by eguzki** [comment] 2019-12-24 16:35
:(

Will check after Christmas

**Comment by eguzki** [comment] 2020-02-28 16:19
Hi,

I have run the import process with the same file from windows host with 3scale v0.16.0 and I see correctly in the dashboard:

`תיאור`: "description"

Please, provide more information. 3scale version and windows version.

**Comment by eguzki** [comment] 2020-03-12 15:30
Closing. Reopen with more information.

**Closed by eguzki** 2020-03-12 15:30 UTC

**Comment by eladmotola** [comment] 2020-03-25 12:29
hey @eguzki , sorry for the long delay
Right now I'm on windows 7 sp 1 and toolbox v0.16.2 I have another host with windows 10 with toolbox v0.13.2
My 3scale version is 2.7
